golemfactory/ya-client

- examples/market_interaction.rs
- src/market.rs
- src/market/provider.rs
- src/web.rs
This facilitates Market API forwarding: https://github.com/golemfactory/yagna/pull/257
- making central service Url public
- making MarketProviderApi clonable (as all other api parts)
Additionally removes some unused field in `WebClientBuilder`.
> Market Api client update

- model/src/activity/activity_state.rs
- model/src/activity/exe_script_command.rs
- specs/activity-api.yaml
- added `ExeScriptCommand::Terminate` for terminating the currently executed script
- removed `State::Active` since it's no longer a valid Activity state
- added `State::Unresponsive` for future use
Updated the Activity OpenAPI spec to reflect recent code changes
> ExeScriptCommand::Terminate and State::Unresponsive

- model/src/payment.rs
- model/src/payment/activity_payment.rs
- model/src/payment/agreement_payment.rs
- model/src/payment/document_status.rs
- model/src/payment/event_type.rs
- model/src/payment/payment.rs
- specs/payment-api.yaml
- src/payment/provider.rs
- src/payment/requestor.rs
Direct relationship with invoices and/or debit notes has been abandoned in favour of `AgreementPayment` and `ActivityPayment`. This still allows to establish which particular invoice and/or debit notes have been covered by a payment. On the other hand, this model is more flexible (e.g. allows making partial payments) and makes payment verification easier.
Fixed return types of payment commands
> Payment relationships changed

- src/error.rs
- src/web.rs
```
[2020-07-02T15:39:32Z ERROR ya_requestor::activity] processing activity for agreement af67c5b4-a93d-4ed0-b1f5-9376c14973f0 failed: AWC JSON payload error: Error that occur during reading payload: A payload reached size limit.
```
Was getting this error when running the yagna core [demo scenario](https://github.com/golemfactory/yagna-integration/tree/master/test/level0/unix).
Added printing of the response body before converting it to JSON, to help debugging JSON errors like above.
> Add debug logging to WebRequest.json

- model/src/payment/activity_payment.rs
- model/src/payment/agreement_payment.rs
- model/src/payment/allocation.rs
- model/src/payment/debit_note.rs
- model/src/payment/invoice.rs
- model/src/payment/payment.rs
- specs/payment-api.yaml
This field will be needed for supporting multiple payment platforms in the payment API. For debit notes, invoices, and payments it is a read-only field. For allocations it can provided during creation but isn't required (will be filled in with default values).
Payment object represents a single (blockchain) transaction. It is possible that it includes activity payments and/or agreement payments from multiple users (but using the same wallet). Therefore, it can be also spending from multiple allocations. To adequately represent this situation `allocation_id` has been removed from `Payment` and added to `ActivityPayment` and `AgreementPayment`.
> Payment API: multi-driver preparations

- specs/market-api.yaml
As per Tech Council action (https://www.notion.so/golemnetwork/87c28c874fc54d76845127946e72e3a7?v=2fe57c56530c41839e6bbcf222c026e2&p=2829f9bebd0549d6839db344b8e41e32) - flat JSON format has been sanctioned as mandatory for Demand/Offer properties.
> [Market API] Flat JSON properties spec added to market-api.yaml

- model/src/activity.rs
- model/src/activity/exe_script_command.rs
- model/src/activity/exe_script_command_result.rs
- model/src/activity/runtime_event.rs
- specs/activity-api.yaml
Introduces a new `capture` parameter to the `RUN` command. The new parameter MUST be included or the output will be discarded.
```json
"run": {
...
"capture": {
"stdout": { "atEnd": { "head": 64000, "format": "bin" } },
"stderr": { "stream": { "limit": 128000, "format": "str" } },
}
}
```
each of `stdout` and `stderr` may contain either:
- `atEnd` - capture output when the command finishes
- optionally limit the captured output size with `"head" | "tail" | "headTail"`, leave blank for unlimited output
- optionally specify output `format` 
- `stream`
- optionally limit the stream output size with `"limit"`, skip for unlimited output
- optionally specify output `format` 
* `capture`: `"stdout" | "stderr"`
* `limit`: `usize`, defaults to null (no limit)
* `format`: `"bin" | "str"`, defaults …
> Runtime output format and capture options

- specs/activity-api.yaml
Do not strictly follow the implementation; the previous structure caused code generator issues
> Fix credentials in ActivityAPI spec

- src/error.rs
- src/market/provider.rs
- src/market/requestor.rs
- src/web.rs
Need to align endpoint urls with [market-api.yaml](../blob/master/specs/market-api.yaml) spec for
- `rejectProposalDemandWithReason`
- `rejectProposalOfferWithReason `
- `cancelAgreementWithReason`
+ better error messages (added HTTP request method to the error)
> Fix broken urls for new endpoints with reason

- specs/market-api.yaml
Partly suggested by @prekucki here:
https://github.com/golemfactory/yagna/pull/765/files#r524684289
> [mkt spec] Make REST responses compliant with standard HTTP Codes semantics

- specs/payment-api.yaml
Fixes a code generation error:
```java
Exception in thread "main" java.lang.RuntimeException: Could not process model 'DebitNoteEvent'.Please make sure that your schema is correct!
at org.openapitools.codegen.DefaultGenerator.generateModels(DefaultGenerator.java:496)
at org.openapitools.codegen.DefaultGenerator.generate(DefaultGenerator.java:1005)
at org.openapitools.codegen.cmd.Generate.execute(Generate.java:431)
at org.openapitools.codegen.cmd.OpenApiGeneratorCommand.run(OpenApiGeneratorCommand.java:32)
at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:61)
Caused by: java.lang.RuntimeException: Invalid inline schema defined in allOf in 'InvoiceReceivedEvent'. Per the OpenApi spec, for this case when a composed schema defines a discriminator, the allOf schemas must …
```
> Event API: Python code generation schema fix

- Cargo.toml
- model/src/payment.rs
- model/src/payment/params.rs
- src/payment/api.rs
- src/web.rs
**Please do not merge until all `event-api/master`'s are properly merged**
Cleanup after event api, no changes to logic.
- Moved query param objects to payments model
- Updated client api to use these for serialisation
- Moved defaults to be set on the server side
> Moved all query string serialization in payment api to 'serde_qs'

- src/payment/api.rs
Using manual joining instead of `url_format_obj` because `serde_qs` doesn't support comma-separated list serialization.
> Fixed serialization of allocation_ids

- .github/workflows/code-check.yml
- .github/workflows/rust.yml
- model/src/payment/debit_note_event.rs
- model/src/payment/invoice_event.rs
- model/src/payment/params.rs
- src/activity/provider.rs
- src/payment/api.rs
conform to [common.yaml](https://github.com/golemfactory/ya-client/blob/master/specs/common.yaml#L7) spec where `pollTimeout` is defined to… have name `timeout`
It also contains changes from `release/v0.6` created by @maaktweluit (but we agree it should be removed).
I'm also turning on CI for `release/*` branches and restoring macOS builds.
> [act,pay] `pollTimeout` has specified name `timeout`

- model/src/node_id.rs
Needed to easily convert `NodeId` into [`H160`](https://docs.rs/ethereum-types/0.12.1/ethereum_types/struct.H160.html#impl-From%3C%26%27a%20%5Bu8%3B%2020%5D%3E):
```rust
addr: H160 = node_id.as_ref().into()
```
> Implemented AsRef<[u8; 20]> for NodeId

- model/src/market.rs
- model/src/market/agreement.rs
- specs/common.yaml
- specs/market-api.yaml
- src/market/provider.rs
- src/market/requestor.rs
Resolves: https://github.com/golemfactory/yagna/issues/1658
`AgreementListEntry` will be used in both GSB and REST API, and ya-client seemed like the best place to put it.
> Add agreement list entry

- model/src/node_id.rs
- src/market/provider.rs
- src/market/requestor.rs
`chrono::Date` is now deprecated and there was an unsound `MaybeUninit` use, which rustc now warns about.
> Fix chrono::Date and MaybeUninit

- src/activity/provider.rs
- src/activity/requestor/control.rs
- src/activity/requestor/state.rs
- src/market/provider.rs
- src/market/requestor.rs
- src/net.rs
- src/payment/api.rs
- src/web.rs
Rust emitted warnings due to the macro expanding as `format!("{}",foo=foo)` when invoked as `url_format("{}",foo)`.
As the intended usage was `url_format("{foo}",foo)` anyway, the recent changes to the format macro allow for a far more ergonomic notation, that being `url_format("{foo}")`. This patch changes the macro to remove expansion of all arguments to named ones, and clearly documents its behavior.
> Fix `url_format`

- Cargo.toml
- examples/allocation_management.rs
- src/payment/api.rs
* The signature of the `amend_allocation` function was wrong -- it should take `NewAllocation` as an argument, which comprises of the read-write fields of the `Allocation` as per the OpenAPI spec.
* Added `allocation_management` example
> Enable amending allocations

- .github/workflows/rust.yml
- Cargo.toml
- model/src/payment.rs
- model/src/payment/debit_note_event.rs
- model/src/payment/invoice_event.rs
- model/src/payment/params.rs
- model/src/payment/payment.rs
- specs/payment-api.yaml
- src/payment/api.rs
The new erc20 driver exposes more information about the status of outbound payments than the previous one. This endpoint exposes this information so that agents can actually reason about them.
> Add payment status endpoint

- specs/identity-api.yaml
- specs/version-api.yaml
`/me` and `/version/get` are already implemented in yagna but are not defined here. In golem-js we pull specs from this repo to auto-generate our http client. Right now, we have to manually add these two endpoints on top of the generated code.
> Add identity and version api spec files

- specs/market-api.yaml
- specs/payment-api.yaml
fix: types on invoice, debit note and agreement collection endpoitns to enumerate possible values and discriminate them
I intended to provide a more specific type information in the OAS. This helps us to build a slightly better ya-ts-client release.
> Correct the types on event returning endpoints for better client-generated typics

- specs/net-api.yaml
The net api spec defines a network as:
```yaml
Network:
type: object
required:
- ip
properties:
id:
type: string
ip:
type: string
mask:
type: string
gateway:
type: string
```
and claims that the `create-network` endpoint takes it as both the request body and return type. This is **not true**
1. The `id` parameter in request body is ignored, the new network always gets assigned a random id
2. The response is guaranteed to have all 4 properties defined
To fix this, I introduced a new component `NewNetwork` to match what's defined in [`model/src/net.rs`](https://github.com/golemfactory/ya-client/blob/master/model/src/net.rs#L19-L34):
```rust
pub struct Network {
pub id: String,
pub ip: String,
pub mask: String,
pub gateway: String,
}
pub struct NewNetwork {
pub ip: String,
pub mask: …
```
> Separate `Network` component into `Network` and `NewNetwork`
