- client/src/market/requestor.rs
> Fix wrong result in wait_for_approval in docs

- model/src/payment/debit_note.rs
- model/src/payment/invoice.rs
- model/src/payment/payment.rs
Signed-off-by: Adam Wierzbicki <awierzbicki@golem.network>
> Use NodeId in Payment API models

- specs/activity-api.yaml
- specs/common.yaml
- specs/market-api.yaml
- specs/payment-api.yaml
- Updated `market-api.yml` to be compatible with the python client generator
- Copied the same security requirements to `payment` and `activity`
> Add `app_key` authentication to all swagger yaml files

- specs/market-api.yaml
> [market-api spec] minor description update

- Cargo.toml
- model/Cargo.toml
- model/src/activity/encrypted.rs
- model/src/activity/sgx_credentials.rs
- specs/activity-api.yaml
- src/activity.rs
- src/activity/requestor/control.rs
- use hex encoding in #39
- add `SgxCredentials::enclave_hash`
- remove `SgxCredentials::session_key`
> SGX: use hex encoding, altered models

- model/src/activity.rs
- model/src/activity/exe_script_command.rs
Prerequisite for multi-file transfers https://github.com/golemfactory/yagna/pull/411
> Multi-file transfer: additional transfer args

- specs/activity-api.yaml
- src/activity/provider.rs
Required by https://github.com/golemfactory/yagna/pull/515
> ActivityProviderApi.get_activity_ids

- Cargo.toml
- model/Cargo.toml
- model/src/activity.rs
- model/src/activity/exe_script_command.rs
- model/src/activity/exe_script_command_result.rs
- model/src/activity/runtime_event.rs
- specs/activity-api.yaml
- src/activity/requestor/control.rs
- src/error.rs
- src/web.rs
Adds support for server sent events.
Includes #32
> Runtime output event stream

- src/market/requestor.rs
> cancel_agreement marked as deprecated

- src/payment/requestor.rs
Updated debit note and invoice input parameters to test a full cycle
Relates to https://github.com/golemfactory/yagna/pull/861
> New invoice filter params

- specs/market-api.yaml
- src/market/provider.rs
- src/market/requestor.rs
Resolves golemfactory/golem-internal#204
> [Event api] Remove deprecated Market endpoints

- model/src/market.rs
- model/src/market/agreement_event.rs
resolves: https://github.com/golemfactory/yagna/issues/868
Related to changes in yagna:
> Created struct with common fields and AgreementEventType enum

- examples/market_interaction.rs
- model/src/error_message.rs
- model/src/market/agreement.rs
- src/market/provider.rs
- src/market/requestor.rs
resolves golemfactory/yagna/issues/874
> [mkt] align HTTP Codes with newest spec

- model/src/payment/account.rs
- specs/payment-api.yaml
Added `driver`, `network`, and `token` properties necessary for simultaneous mainnet/testnet support.
> Payment: Additional properties for Account model

- model/src/payment/params.rs
Closes https://github.com/golemfactory/yagna/issues/919
JIRA's PAY-191
Hope this is the correct repo ;)
> Change defaults for timeouts

- specs/payment-api.yaml
A copy of #101 (because CI checks don't run on that one).
> Updated Payment API specs to reflect current code state.

- Cargo.toml
- model/src/market/reason.rs
- src/web.rs
Linked with https://github.com/golemfactory/yagna/pull/1188
> Update awc to 2.0

- .github/CODEOWNERS
As decided on Tech Council @ 2021.04.22
> Code ownership settlement

- model/src/node_id.rs
Very handy conversion used a lot in ya-relay
https://github.com/golemfactory/ya-relay/pull/76
> Add TryFrom &Vec<u8> to NodeId

- model/src/activity/activity_state.rs
- model/src/activity/activity_usage.rs
- model/src/activity/exe_script_command.rs
- model/src/activity/exe_script_command_result.rs
- model/src/activity/exe_script_command_state.rs
- model/src/activity/exe_script_request.rs
- model/src/activity/provider_event.rs
- model/src/error_message.rs
- specs/activity-api.yaml
- specs/market-api.yaml
- Added "capture" to Run ExeScript command struct in Activity API yaml
- Removed references to gdocs, replaced with references to golem gitbook
> Updated Market API and Activity API yamls

- model/src/net.rs
- specs/net-api-v2.yaml
- specs/net-api.yaml
- src/cli.rs
- src/net.rs
resolves: https://github.com/golemfactory/yagna/issues/1882
> Net API v2

- specs/payment-api.yaml
It fixes https://github.com/golemfactory/ya-client/issues/122
> add 410 error code to DELETE allocation docs

- model/src/market/agreement.rs
- specs/common.yaml
- specs/market-api.yaml
Apply changes requested in #124, tracked in #126.
> API consistency fixes

- .github/workflows/rust.yml
Partially resolves https://github.com/golemfactory/yagna/issues/2294
> move rust version to env variable

- specs/common.yaml
- specs/gsb-api.yaml
- specs/net-api-v2.yaml
- specs/net-api.yaml
API key authorization token. WebSocket endpoints authorized using API key.
Resolves https://github.com/golemfactory/yagna/issues/2510
Linked with https://github.com/golemfactory/yagna/pull/2504
> API key authorization token.

- .github/workflows/rust.yml
- examples/activity_interaction.rs
- examples/market_interaction.rs
- model/src/activity/activity_state.rs
- model/src/activity/encrypted.rs
- model/src/activity/exe_script_command.rs
- model/src/activity/sgx_credentials.rs
- model/src/node_id.rs
- model/src/payment.rs
- model/src/payment/debit_note_event.rs
- model/src/payment/invoice_event.rs
- model/src/payment/params.rs
- model/src/payment/rejection_reason.rs
- src/activity/provider.rs
- src/activity/requestor/control.rs
- src/net.rs
- src/web.rs
Resolves https://github.com/golemfactory/yagna/issues/2438
> Bump rust + fix some clippy

- model/src/payment/debit_note_event.rs
- model/src/payment/invoice_event.rs
- model/src/payment/payment.rs
- specs/payment-api.yaml
> Add DriverStatusProperty to {DebitNote,Invoice}EventType

- specs/activity-api.yaml
- src/activity/provider.rs
* spec: add provider & requestor_state tags
* implementation: get_agreement_id -> get_activity_agreement
> Fix getActivityAgreement

- specs/payment-api.yaml
* add operationId to /payments/status.
* remove dead PaymentReceived event.
> spec: payment cleanup

- model/Cargo.toml
- model/src/payment.rs
- model/src/payment/payment.rs
- src/payment/api.rs
- src/web.rs
resolves: https://github.com/golemfactory/gamerhash-facade/issues/44
> [!WARNING]
Don't merge before new endpoint will be tested
> payments with signed bytes

- examples/allocation_management.rs
- model/src/payment/allocation.rs
- model/src/payment/params.rs
- src/payment/api.rs
Also fix breaking change with timeout param
> Make allocations compatible with deposits

- specs/payment-api.yaml
> fix: add missing fileds

- specs/market-api.yaml
Reverts golemfactory/ya-client#172
> Revert "fix: changed the counterProposalDemand and counterProposalOffer responses to match what the implementation does"
